### ISSUE TITLE
what does cmd stand for ?

### ISSUE THREAD

**Issue by crosofg** [fivdi/i2c-bus#15]
Hi 
What does cmd stand for ?
```
bus.writeByteSync(addr, cmd, byte)
```

**Comment by fivdi** [comment]
The SMBus write byte protocol, which is implemented by writeByteSync, can be used to send a byte sized command code and a byte of data. Depending on the documentation the term register may be used instead of command. For example, many documents form Atmel use the term command. For a short description of the various SMBus protocols see section 2.3 on page 3 of [AVR316](http://www.atmel.com/Images/doc2583.pdf).

**Comment by fivdi** [comment]
I'm going to assume things have been cleared up here and close this one.
