### ISSUE TITLE
Ability to develop on other platform

### ISSUE THREAD

**Issue by Y0nnyy** [fivdi/i2c-bus#59]
As a developer i want to develop my code on another machine which my run on Windows or MacOS. 

Currently it is not possible to install this dependency on any other machine than Linux (right?).

So what is a correct approach to develop a software with this dependency on a machine which does not run on Linux?

**Comment by fivdi** [comment]
> Currently it is not possible to install this dependency on any other machine than Linux (right?).

Yes, this is correct.

> So what is a correct approach to develop a software with this dependency on a machine which does not run on Linux?

One way to do this would be to have `i2c-bus` in the "optionalDependencies" rather than in the "dependencies" in your `package.json`. Error messages will still be displayed but `npm install` should continue rather than terminate with error.

A potential alternative approach is described at https://github.com/rwaldron/johnny-five/issues/1415#issuecomment-345313073

Out of curiosity, have you being using `i2c-bus` for quite some time? If so, is this a new issue that didn't occur in the past and has only started to occur recently?

**Comment by fivdi** [comment]
> So it would be nice to inject a mock at build-time. Or how do you handle testing?

Instead of doing this in your tests:
```js
const i2c = require('i2c-bus');
```
do something like this:
```js
const i2c = require('./i2c-bus-mock.js');
```
You would or course need to implement `i2c-bus-mock.js`

**Comment by Y0nnyy** [comment]
Yes, but i also want to test my application by running it. 
For other that may have the same question: I solved this by injecting it at built-time. I am using Webpack and created a new webpack-config just for development. 
And there i added under ``resolve.alias`` follwing:
``
'i2c-bus': path.join(__dirname, 'mocks/i2c-bus-mock.ts'),
``
This mock has just those functions i use and do nothing. 

It think it would be very nice if this package would provide a mock itself, wich is a little bit more advanced and does not rely on hardware. What do you think @fivdi?

Other than that, this issue can be closed from my side :)

**Comment by fivdi** [comment]
> It think it would be very nice if this package would provide a mock itself

Yes. However, it could also be implemented as a separate package. It's not something that will be added to i2c-bus in the near future so I'm going to go ahead and close the issue.
